


all: part1_serial part1_omp part2_serial part2_omp

part1_serial: hwk2part1_serial.cpp
	g++ hwk2part1_serial.cpp -o p1s

part1_omp: hwk2part1_omp.cpp
	g++ -fopenmp hwk2part1_omp.cpp -o p1o


part2_serial: hwk2part2_serial.cpp
	g++ hwk2part2_serial.cpp -o p2s



part2_omp: hwk2part2_omp.cpp
	g++ -fopenmp hwk2part2_omp.cpp -o p2o
